FROM python:3.11-slim as builder
RUN apt update && \
    apt install --no-install-recommends -y build-essential gcc git && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /builder

RUN git clone https://github.com/hzwer/Practical-RIFE.git .
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir torch==2.5.0+cu124 torchvision==0.20.0+cu124 torchaudio==2.5.0 --index-url https://download.pytorch.org/whl/cu124
RUN pip install --no-cache-dir -r requirements.txt

# Stage 2: Runtime
FROM nvidia/cuda:12.4.0-runtime-ubuntu20.04

RUN apt update && \
    apt install --no-install-recommends -y software-properties-common ffmpeg libgl1 libsm6 libxext6 libxrender-dev && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt install --no-install-recommends -y python3.11 python3-distutils && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11 && \
    apt clean && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages

WORKDIR /app

COPY Snakes15FPS360p.mp4 /video_data/
COPY server.py /app/
COPY train_log /app/


RUN pip install --no-cache-dir flask
EXPOSE 5000

CMD ["python3", "/app/server.py"]